/** Headless game simulation. Do not import vue, pinia, or pixi.js from this folder. */
export {
  advanceTowerBuilds,
  createGrid,
  damageBlocker,
  damageObstacle,
  damageTower,
  DEFAULT_GRID_COLS,
  DEFAULT_GRID_ROWS,
  DEFAULT_VIEWPORT_PADDING,
  fitGridToViewport,
  forEachTile,
  getObstacle,
  getTower,
  hasObstacle,
  hasTower,
  inBounds,
  isBlocked,
  obstacleMaxHp,
  OBSTACLE_KINDS,
  OBSTACLE_MAX_HP,
  placeTower,
  removeTower,
  sameTile,
  tileKind,
  toggleTower,
  TOWER_MAX_HP,
  upgradeTower,
  viewportToTile,
  withTowers,
} from "./grid";
export type {
  Grid,
  GridLayout,
  Obstacle,
  ObstacleDef,
  ObstacleKind,
  TileCoord,
  TileKind,
  Tower,
} from "./grid";
export { findPath, isWalkable } from "./path";
export type { Path, PathOptions } from "./path";
export {
  createBattleGrid,
  createMapGrid,
  getGameMap,
  isMapId,
  WORLD_MAP_COUNT,
  WORLD_MAPS,
} from "./maps";
export type { GameMapDef, MapId } from "./maps";
export {
  campaignMapStatuses,
  createCampaign,
  currentStage,
  isMapCleared,
  isMapUnlocked,
  mapIdForStage,
  playableStage,
  recordVictory,
  saveMapTowers,
  towersForMap,
} from "./campaign";
export type { CampaignMapStatus, CampaignProgress } from "./campaign";
export {
  CAMPAIGN_STORAGE_KEY,
  loadCampaign,
  parseCampaign,
  persistCampaign,
  serializeCampaign,
} from "./save";
export type { CampaignStore } from "./save";
export {
  ALLY_GOLD_REWARD,
  START_GOLD,
  START_GOLD_PER_STAGE,
  startingGold,
  BASE_MAX_HP,
  BUILD_DURATION_SEC,
  canUpgrade,
  CATCH_RANGE_TILES,
  createSim,
  DEFAULT_TOWER_TYPE,
  ENEMY_BASE_DAMAGE,
  hudSnapshot,
  isTowerComplete,
  PHASE_DURATION_SEC,
  SPAWN_INTERVAL_SEC,
  setTimeScale,
  simBeginBuild,
  simRemoveTower,
  simToggleTower,
  simUpgradeTower,
  tick,
  TIME_SCALES,
  TOWER_ATTACK_DPS,
  TOWER_FIRE_INTERVAL_SEC,
  TOWER_ATTACK_LABELS,
  TOWER_CATALOG,
  TOWER_DEFS,
  TOWER_MAX_LEVEL,
  TOWER_RANGE_TILES,
  TOWER_TYPE_IDS,
  towerAttack,
  towerBuildCost,
  towerDps,
  towerFires,
  towerMaxHp,
  towerRange,
  towerSlowFactor,
  towerSlowSec,
  towerSplashRadius,
  towerUpgradeCost,
  towerWorkDuration,
  UPGRADE_DURATION_SEC,
  UNIT_ATTACK_DPS,
  UNIT_MAX_HP,
  unitTile,
  WAVE_SIZE,
  BATTLE_WAVE_COUNT,
  ENEMY_BEHAVIOR_IDS,
  ENEMY_BEHAVIOR_LABELS,
  ENEMY_SPRITE_LABELS,
  ENEMY_TYPE_IDS,
  DEFAULT_ENEMY_BEHAVIOR,
  BREAKER_HUE,
  MAX_ENEMIES,
  MIN_ENEMIES,
  bundledEnemyTable,
  cloneEnemyTable,
  defaultEnemy,
  findEnemyIdForStats,
  getEnemy,
  getEnemyCatalog,
  getEnemyTable,
  nextEnemyId,
  parseEnemyTable,
  parseEnemyTableJson,
  resetEnemyTable,
  serializeEnemyTable,
  setEnemyTable,
  shiftHue,
  tryGetEnemy,
  normalizeHue,
  getStageWave,
  STAGE_COUNT,
  MIN_WAVE_STAGES,
  MAX_WAVE_STAGES,
  MAX_WAVE_SPAWNS_PER_BURST,
  campaignCycle,
  previousCycleStage,
  enemySpeedMultiplier,
  bundledWaveTable,
  cloneWaveTable,
  defaultStageWave,
  defaultWaveBurst,
  defaultWaveSpawn,
  enemyCount,
  allySpawnDurationSec,
  enemySpawnDurationSec,
  PHASE_TAIL_SEC,
  tightPhaseSec,
  getWaveTable,
  insertWaveSpawn,
  maxEnemyHp,
  moveWaveSpawn,
  parseWaveTable,
  parseWaveTableJson,
  resetWaveTable,
  serializeWaveTable,
  setWaveTable,
  waveEnemyIds,
  waveStageCount,
} from "./sim";
export type {
  BattleOutcome,
  CommandResult,
  EnemyBehaviorId,
  EnemyDef,
  EnemyTable,
  EnemyTypeId,
  HudSnapshot,
  ParseEnemyResult,
  ParseWaveResult,
  Phase,
  SimState,
  StageWave,
  StageWaveRow,
  TimeScale,
  TowerAttackId,
  TowerDef,
  TowerLevelStats,
  TowerShot,
  TowerTypeId,
  Unit,
  UnitKind,
  WaveBurst,
  WaveBurstRow,
  WaveSpawn,
  WaveSpawnRef,
  WaveTable,
} from "./sim";
