/** Headless game simulation. Do not import vue, pinia, or pixi.js from this folder. */
export {
  advanceTowerBuilds,
  createGrid,
  damageTower,
  DEFAULT_GRID_COLS,
  DEFAULT_GRID_ROWS,
  DEFAULT_VIEWPORT_PADDING,
  fitGridToViewport,
  forEachTile,
  getTower,
  hasTower,
  inBounds,
  placeTower,
  sameTile,
  tileKind,
  toggleTower,
  TOWER_MAX_HP,
  upgradeTower,
  viewportToTile,
} from "./grid";
export type { Grid, GridLayout, TileCoord, TileKind, Tower } from "./grid";
export { findPath, isWalkable } from "./path";
export type { Path } from "./path";
export {
  ALLY_GOLD_REWARD,
  START_GOLD,
  BASE_MAX_HP,
  BUILD_DURATION_SEC,
  canUpgrade,
  CATCH_RANGE_TILES,
  createSim,
  DEFAULT_TOWER_TYPE,
  ENEMY_BASE_DAMAGE,
  hudSnapshot,
  isTowerComplete,
  PHASE_DURATION_SEC,
  SPAWN_INTERVAL_SEC,
  setTimeScale,
  simBeginBuild,
  simToggleTower,
  simUpgradeTower,
  tick,
  TIME_SCALES,
  TOWER_ATTACK_DPS,
  TOWER_FIRE_INTERVAL_SEC,
  TOWER_ATTACK_LABELS,
  TOWER_CATALOG,
  TOWER_DEFS,
  TOWER_MAX_LEVEL,
  TOWER_RANGE_TILES,
  TOWER_TYPE_IDS,
  towerAttack,
  towerBuildCost,
  towerDps,
  towerMaxHp,
  towerRange,
  towerSlowFactor,
  towerSlowSec,
  towerSplashRadius,
  towerUpgradeCost,
  towerWorkDuration,
  UPGRADE_DURATION_SEC,
  UNIT_ATTACK_DPS,
  UNIT_MAX_HP,
  unitTile,
  WAVE_SIZE,
  ENEMY_TYPE_IDS,
  getStageWave,
  STAGE_COUNT,
} from "./sim";
export type {
  CommandResult,
  EnemyTypeId,
  HudSnapshot,
  Phase,
  SimState,
  StageWave,
  TimeScale,
  TowerAttackId,
  TowerDef,
  TowerLevelStats,
  TowerShot,
  TowerTypeId,
  Unit,
  UnitKind,
  WaveBurst,
} from "./sim";
